### ISSUE TITLE
MongoDB Setup and .env Setup documentation is missing?

### ISSUE THREAD

**Issue by jmschrack** [Pythagora-io/api#3]
The current documentation doesn't mention needing to set up a MongoDB cluster or the proper way to set up the .env file.

For MongoDB, I set up a free cluster on [MondoDB Atlas](https://www.mongodb.com/cloud/atlas?tck=docs_server) 
It looks like you're only using it for the express-session store. Can this be made optional? (Express defaults to MemoryStore.)

There's no info on how to setup the .env file.  It seems like the current route is to rename `.example.env` to `.env` and remove GITHUB_CLIENT_ID, GITHUB_CLIENT_SECRET, GOOGLE_CLIENT_ID, GOOGLE_CLIENT_SECRET.  And then set MONGDODB_URL appropriately.

**Comment by LeonOstrez** [comment]
Thank you for checking out repo and opening issue! I added extra explanation in Readme that it's needed to create .env.

Regarding mongo, it is used to store multiple things:

- users data (who has access to api)
- sessions
- tracking api calls
- telemetries
