### ISSUE TITLE
Support gpt-3.5-turbo

### ISSUE THREAD

**Issue by jmschrack** [Pythagora-io/api#4]
Can we define which gpt model to use?

I was able to get gpt-3.5-turbo  working by changing the model to `gpt-3.5-turbo-0613`
 in: https://github.com/Pythagora-io/api/blob/61814f6a4191b84a6a82fd1f7a54e3bee84588f9/helpers/openai.js#L32-L37   
and setting `MAX_GPT_MODEL_TOKENS: 4097` 
in: https://github.com/Pythagora-io/api/blob/61814f6a4191b84a6a82fd1f7a54e3bee84588f9/const/common.js#L1-L4

It worked fine for me, and generated some useful test cases.  I don't have access to gpt-4 personally, and the gpt-3.5-turbo-0613 is currently the highest rate limits (at time of writing).

**Comment by LeonOstrez** [comment]
Hi @jmschrack we are using only GPT4 because all other models give significantly worse results. Our prompts were created using and testing GPT4 so we highly recommend using only that model for now. There are some other limitations that are different like you mentioned MAX_GPT_MODEL_TOKENS...
